#!/bin/sh
gnome-keyring-daemon --start --components=secrets &
if command -v dbus-launch > /dev/null && test -z "${DBUS_SESSION_BUS_ADDRESS}"
then
 	eval $(dbus-launch --sh-syntax --exit-with-session)
fi

~/.fehbg &
picom &
dunst &
bar &
gentoo-pipewire-launcher &

exec dwm
